### ISSUE TITLE
Fatal Error on activation

### ISSUE THREAD

**Issue by lukecav** [TheLookandFeel/listings-jobs#31]
Fatal error: Class 'Listings\Admin\Metabox' not found in /srv/www/wordpress-default/wp-content/plugins/listings-jobs/src/Admin/Metaboxes/JobDetails.php on line 8

https://github.com/TheLookandFeel/listings-jobs/blob/master/src/Admin/Metaboxes/JobDetails.php#L8

**Comment by kishoresahoo** [comment]
YES I got the same

**Comment by coenjacobs** [comment]
Sorry about that. Something went wrong with the deployment of the supporting Listings core update. I'll get that out as soon as I can. Thanks for reporting.

**Comment by coenjacobs** [comment]
This has been fixed now. Make sure you run Listings core version 0.3.0. We've also made Listings Jobs version 0.2.1 that fixes a metabox saving issue.

**Comment by kishoresahoo** [comment]
Thanks fixing it quickly. I have tested it. Is there roadmap for the job plugin. How you are going to add resume etc to this.As a separate add-on or ?

**Comment by scottbasgaard** [comment]
Hey @kishoresahoo :)

We're doing our best to get a proper roadmap together and we'll make sure to post that out on http://develop.wplistings.com/ once it's ready.

You should also make sure to subscribe to the Listings newsletter on http://wplistings.com/ as we'll make sure to send out updates there as well.

In terms of add-ons resumes are on our list along with paid listings for jobs.

Appreciate your input and feedback here lately!

Scott

**Comment by lukecav** [comment]
@scottbasgaard 

Thanks for fixing that issue, no issues so far in the updated version.

**Comment by scottbasgaard** [comment]
@lukecav props to @coenjacobs and great to hear it's working.

Again, appreciate your help here as well.

Wish you the best and do let us know if anything else does come up :)
